### ISSUE TITLE
[wct-local] Can't run tests on Firefox 63

### ISSUE THREAD

**Issue by usergenic** [Polymer/tools#751]
This is a persistent reliable error now after the Firefox 63 release.
```
{
  "value": {
    "stacktrace": `
org.openqa.selenium.WebDriverException: newSession
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'redacted', ip: '192.168.128.55', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_112'
Driver info: driver.version: unknown
remote stacktrace: WebDriverError@chrome://marionette/content/error.js:178:5
UnknownCommandError@chrome://marionette/content/error.js:472:5
despatch@chrome://marionette/content/server.js:290:13
execute@chrome://marionette/content/server.js:271:11
onPacket/<@chrome://marionette/content/server.js:246:15
onPacket@chrome://marionette/content/server.js:245:8
_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
    at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
    at org.openqa.selenium.remote.server.RemoteSession$Factory.performHandshake(RemoteSession.java:145)
    at org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:159)
    at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:176)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
    at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:179)
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:65)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.Collections$2.tryAdvance(Collections.java:4717)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:68)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)
    at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
    tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
    at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:71)
    at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$1(WebDriverServlet.java:246)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
`,
    "stackTrace": [
      {
        "fileName": "NativeConstructorAccessorImpl.java",
        "methodName": "newInstance0",
        "className": "sun.reflect.NativeConstructorAccessorImpl",
        "lineNumber": -2
      },
      {
        "fileName": "NativeConstructorAccessorImpl.java",
        "methodName": "newInstance",
        "className": "sun.reflect.NativeConstructorAccessorImpl",
        "lineNumber": 62
      },
      {
        "fileName": "DelegatingConstructorAccessorImpl.java",
        "methodName": "newInstance",
        "className": "sun.reflect.DelegatingConstructorAccessorImpl",
        "lineNumber": 45
      },
      {
        "fileName": "Constructor.java",
        "methodName": "newInstance",
        "className": "java.lang.reflect.Constructor",
        "lineNumber": 423
      },
      {
        "fileName": "W3CHandshakeResponse.java",
        "methodName": "lambda$new$0",
        "className": "org.openqa.selenium.remote.W3CHandshakeResponse",
        "lineNumber": 57
      },
      {
        "fileName": "W3CHandshakeResponse.java",
        "methodName": "lambda$getResponseFunction$2",
        "className": "org.openqa.selenium.remote.W3CHandshakeResponse",
        "lineNumber": 104
      },
      {
        "fileName": "ProtocolHandshake.java",
        "methodName": "lambda$createSession$0",
        "className": "org.openqa.selenium.remote.ProtocolHandshake",
        "lineNumber": 123
      },
      {
        "fileName": "ReferencePipeline.java",
        "methodName": "accept",
        "className": "java.util.stream.ReferencePipeline$3$1",
        "lineNumber": 193
      },
      {
        "fileName": "Spliterators.java",
        "methodName": "tryAdvance",
        "className": "java.util.Spliterators$ArraySpliterator",
        "lineNumber": 958
      },
      {
        "fileName": "ReferencePipeline.java",
        "methodName": "forEachWithCancel",
        "className": "java.util.stream.ReferencePipeline",
        "lineNumber": 126
      },
      {
        "fileName": "AbstractPipeline.java",
        "methodName": "copyIntoWithCancel",
        "className":"java.util.stream.Abstract
```

**Comment by nathfisher** [comment]
A workaround that worked for me was to add the test url to `browserOptions.firefox` in .wct.conf.json

```
{
  "plugins": {
    "local": {
        "browsers": ["chrome","firefox"],
        "browserOptions": {
            "chrome": [
              "window-size=1920,1080",
              "headless",
              "disable-gpu"
            ],
            "firefox": [
              "http://localhost:8081/components/my-element/generated-index.html?cli_browser_id=1",
              "--headless"
            ]
          }
    }
  }
}
```

**Comment by usergenic** [comment]
Fixed in #754

**Comment by usergenic** [comment]
Also polymer-cli@1.8.1 includes updated wct-local@2.1.3 in shrinkwrap which fixes this.

**Comment by hellokatili** [comment]
@usergenic This error still occurs with polymer-cli@1.9.6 which includes wct-local@2.1.3 with Firefox 66.
